{{- define "homelab.env-extsec-hugo" -}}
{{- $refreshInterval := "24h" -}}
{{- $secretStoreName := "op-cluster-secret-store" -}}
{{- $envSecrets := dict -}}
{{- with .Values.externalSecretsConfig }}
{{- $refreshInterval = (.refreshInterval | default "24h") -}}
{{- $secretStoreName = (.secretStoreName | default "op-cluster-secret-store") -}}
{{- $envSecrets = (.envSecrets | default dict) -}}
{{- end }}
{{- if gt (len $envSecrets) 0 }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.componentName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "homelab.labels-hugo" . | nindent 4 }}
spec:
  refreshInterval: {{ $refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $secretStoreName }}
  target:
    name: {{ .Values.componentName }}-env-extsec
    creationPolicy: Owner
  data:
    {{- range $key, $val := $envSecrets }}
    - secretKey: {{ $key | toString }}
      remoteRef:
        key: {{ $val | toString }}
    {{- end }}
{{- end }}
{{- end -}}
